# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: melsahha <melsahha@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/04 17:23:57 by melsahha          #+#    #+#              #
#    Updated: 2022/10/04 21:13:53 by melsahha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ft_display_file:
	gcc -Wall -Wextra -Werror ft_display_file.c -o ft_display_file

all: ft_display_file

clean:
	rm -f ft_display_file.o

fclean: clean
	rm -f ft_display_file

re: fclean all
