# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: melsahha <melsahha@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/10/04 21:21:46 by melsahha          #+#    #+#              #
#    Updated: 2022/10/04 21:33:36 by melsahha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

ft_cat:
	gcc -Wall -Wextra -Werror ft_cat.c -o ft_cat

all: ft_cat

clean:
	rm -f ft_cat.o

fclean: clean
	rm -f ft_cat

re: fclean all
